# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WWF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "VK-ios-sdk" 
  pod 'SwiftyVK'
  # Pods for WWF

end
